L9 app logic
Dmitry-Co/testGuru pull request #11
Opened 2023-11-20 14:42 UTC by Dmitry-Co

2023-11-20 17:23 UTC, BubuntuClu requested changes

2023-11-20 17:23 UTC, BubuntuClu commented on app/views/answers/new.html.erb
> +<%= link_to 'Back', question_path(@question) %>
ты создаешь ответ, от ассоциации вопроса. можншь сделать `@answer.question` и тогда эту строку можно вынести в паршиал

2023-11-20 17:23 UTC, BubuntuClu commented on app/views/answers/_form.html.erb
> +<% end %>
видишь тут красный знак нарисован у последней строки? это ругается гитхаб, что нет пустой строки в конце файла. в IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2023-11-20 17:23 UTC, BubuntuClu commented on app/views/questions/_question.html.erb
> +   <td><%= link_to 'Show', question_path %></td>
тебе параметр надо передать в путь

2023-11-21 14:50 UTC, Dmitry-Co commented on app/views/questions/_question.html.erb
> +   <td><%= link_to 'Show', question_path %></td>
добавил, заработало, спасибо)

2023-11-21 14:50 UTC, Dmitry-Co commented on app/views/answers/_form.html.erb
> +<% end %>
добавил)

2023-11-21 14:57 UTC, Dmitry-Co commented on app/views/answers/new.html.erb
> +<%= link_to 'Back', question_path(@question) %>
не до конца понял смысл. 
добавлю @answer.question в путь и получим 
<%= link_to 'Back', question_path(@answer.question) %> и создам новый паршэл добавив строку в него. верно?

далее его рендерить в app/views/answers/new.html.erb. но для чего? чтобы видеть ссылку Back во вьхах ответов?

или нужно будет рендерить этот паршал во всех трех файлах new.html.erb (тесты, вопросы, ответы)?

2023-11-25 17:08 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_update -> {self.current_question = next_question}
это что за синтаксис, что-то мне незнакомое. у тебя ведь вот метод `before_validation_set_question` который делает нужное действие. тебе нужно его вызывать для `create/update`

2023-11-25 17:08 UTC, BubuntuClu commented on app/models/user.rb
> +  # has_many :tests_users
ненужный код сразу удаляй

2023-11-25 17:08 UTC, BubuntuClu commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "scaffold", "data-turbo-track": "reload" %>
зачем эта строка?

2023-11-26 10:09 UTC, Dmitry-Co commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "scaffold", "data-turbo-track": "reload" %>
тестировал как работает(не удалил), если явно указывать подключение стиля, помимо диррективы в манифест файле.

2023-11-26 11:11 UTC, Dmitry-Co commented on app/models/test_passage.rb
> +  before_update -> {self.current_question = next_question}
правильно ли я понял:
добавил :update в before_validation :before_validation_set_question, on: [:create, :update]

2023-12-08 04:31 UTC, merged