L10 authentication
Dmitry-Co/testGuru pull request #12
Opened 2023-12-09 07:27 UTC by Dmitry-Co

2023-12-09 18:43 UTC, BubuntuClu requested changes

2023-12-09 18:43 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирование роутов на 6 и 7 строке

2023-12-13 11:30 UTC, Dmitry-Co commented on config/routes.rb
> +  get 'users/new'
поправил)

2023-12-13 18:04 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: EMAIL }, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2023-12-14 05:56 UTC, Dmitry-Co commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: EMAIL }, uniqueness: true
точно, где-то у нас при валидации уже всплывала тема, что нужно и в приложении и в БД устанавливать ограничение, спасибо! добавил

2023-12-14 06:01 UTC, merged