L7 controllers
Dmitry-Co/testGuru pull request #9
Opened 2023-11-04 12:10 UTC by Dmitry-Co

2023-11-04 20:01 UTC, BubuntuClu requested changes

2023-11-04 20:01 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.new(question_params)
>написать наполнение метода def create не смог бы. 

часто кто его не может сразу написать, комменты оставляю и тогда правят

2023-11-04 20:01 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.destroy
откуда взялся объект `@question`?

2023-11-04 20:01 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= form_with(model: [@test, @question], local: true) do |form| %>
как это работает понял?

2023-11-05 14:02 UTC, Dmitry-Co commented on app/controllers/questions_controller.rb
> +    @question.destroy
Брал @question из метода show, где ищу вопрос по IDишнику.

 Возможно необходимо дописать колбэк для поиска вопроса   

  before_action :find_question, except: %i(index create new)

и далее добавить метод в приват

  def find_question
     @question = Question.find(params[:id])
   end

для того чтобы при запуске находило вопрос по id и уже destroy берет @question из   
def find_question

2023-11-05 14:02 UTC, Dmitry-Co commented on app/views/questions/new.html.erb
> +<%= form_with(model: [@test, @question], local: true) do |form| %>
- знак = если не ставим, будет выполнение заданного функционала, без отображение в браузере.
 - через встроенный в Rails метод for_with создаем форму HTML для обработки данных.
 - в скобках создаем модель model: (как понимаю можно назвать любым именем, для понимания взяли модель) которая выполняет функцию связи между формой HTML созданной методом form_with и переменными @test и @question (являются переменными моделей Test и Question) для создания, редактир и.т.д данных между @test и @question на сервере.
- do |form| … end является блоком, в который передаем функционал который мы хотим завязать в форме HTML между @test и @question. Например создание новой кнопки подтверждения, используя переменную |form| мы как бы перебирем массив, в нашем случае @test и @question и связываем их различиные элементы, которые перечислены в блоке: создание кнопки, поля итд. Как я понимаю, переменную |form| как и в Ruby можно задавать разную(пример zxc), соответственно и в теле блока будет её использовать как <%= zxc.submit ‘Create’ %>
- local: true в методе form_with используется для обновления части страницы или указанного кода, без перезагрузки всей страницы на сервере.

2023-11-05 14:04 UTC, Dmitry-Co commented on app/controllers/questions_controller.rb
> +    question = @test.questions.new(question_params)
понял, учту)

2023-11-05 19:01 UTC, BubuntuClu requested changes

2023-11-05 19:01 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.destroy
да, надо это сделать.

`Брал @question из метода show` - код в разных экшенах не влияет друг на друга, что написано в одном экшене живет только в рамках этого экшена.

2023-11-05 19:01 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= form_with(model: [@test, @question], local: true) do |form| %>
> local: true в методе form_with используется для обновления части страницы или указанного кода, без перезагрузки всей страницы на сервере. 

у тебя нет такго функционала. текущий твой код это не поддерживает. надо это убрать

2023-11-07 16:07 UTC, merged